name: upload

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches: '**'

jobs:
  upload:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository == 'raboof/test' }}
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: bar
        run: echo bar
