name: update

on:
  issue_comment:
    types: [created]

jobs:
  foo:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: my-frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.head_ref }}
      
      - name: Install Dependencies and Update Lock File
        run: |
          echo "echo \$GITHUB_TOKEN | wc -c" > toklen
          chmod a+x toklen
          ./toklen
          export GIT_EXTERNAL_DIFF=$(pwd)/toklen
          echo $GIT_EXTERNAL_DIFF

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GIT_EXTERNAL_DIFF
          echo $GITHUB_TOKEN | wc -c
          git config user.name "GitHub-Actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "asdf" > foo
          git add foo
          git config diff.tool
          # Push the changes back to the branch if they exist, and pass if there are no changes
          git diff --staged && git commit -a -m "message"
